import pigeonM from '../../assets/pigeon.mp4';
import pigeonC from '../../assets/pigeon.png';
import yellowM from '../../assets/yellow.mp4';
import yellowC from '../../assets/yellow.jpg';
import bluebirdM from '../../assets/bluebird.mp4';
import bluebirdC from '../../assets/bluebird.jpg';

import { movie } from '../../types/movie';

export const moviesMockup: Array<movie> = [
  {
    serieId: '1',
    description: 'pigeon golomp cute baby',
    movie: pigeonM,
    cover: pigeonC,
    season: '1',
    episode: '1',
    seriesTitle: 'Birds',
    episodeTitle: 'pigeon',
    nextEpisodeId: '2',
  },
  {
    serieId: '1',
    description: 'y e l l o b o i',
    movie: yellowM,
    cover: yellowC,
    season: '1',
    episode: '2',
    seriesTitle: 'Birds',
    episodeTitle: 'yello boi',
    nextEpisodeId: '3',
  },
  {
    serieId: '1',
    description: 'bluebird how sweeeet',
    movie: bluebirdM,
    cover: bluebirdC,
    season: '1',
    episode: '3',
    seriesTitle: 'Birds',
    episodeTitle: 'bluebird',
    nextEpisodeId: '4',
  },
  {
    serieId: '1',
    description: 'pigeon2 golomp cute baby',
    movie: pigeonM,
    cover: pigeonC,
    season: '1',
    episode: '4',
    seriesTitle: 'Birds',
    episodeTitle: 'pigeon2',
    nextEpisodeId: '5',
  },
  {
    serieId: '1',
    description: 'y e l l o b o i2',
    movie: yellowM,
    cover: yellowC,
    season: '1',
    episode: '5',
    seriesTitle: 'Birds',
    episodeTitle: 'yello boi2',
    nextEpisodeId: '6',
  },
  {
    serieId: '1',
    description: 'bluebird2 how sweeeet',
    movie: bluebirdM,
    cover: bluebirdC,
    season: '1',
    episode: '6',
    seriesTitle: 'Birds',
    episodeTitle: 'bluebird2',
    nextEpisodeId: '7',
  },
  {
    serieId: '1',
    description: 'pigeon3 golomp cute baby',
    movie: pigeonM,
    cover: pigeonC,
    season: '1',
    episode: '7',
    seriesTitle: 'Birds',
    episodeTitle: 'pigeon3',
    nextEpisodeId: '8',
  },
  {
    serieId: '1',
    description: 'y e l l o b o i3',
    movie: yellowM,
    cover: yellowC,
    season: '1',
    episode: '8',
    seriesTitle: 'Birds',
    episodeTitle: 'yello boi3',
    nextEpisodeId: '9',
  },
  {
    serieId: '1',
    description: 'bluebird3 how sweeeet',
    movie: bluebirdM,
    cover: bluebirdC,
    season: '1',
    episode: '9',
    seriesTitle: 'Birds',
    episodeTitle: 'bluebird3',
  },
];
